project:
  type: website
  output-dir: .

website:
  title: "Hana Website"
  navbar:
    left:
      - text: About Me
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



